POST http://jobsify.dev/api/users/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "password1234"
}

###

POST http://jobsify.dev/api/users/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "password1234"
}

###

GET http://jobsify.dev/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkN2QwZmMzMGViYTk2Yjg3MTRjOTlkIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJ1c2VyIn0sImlhdCI6MTY1ODMxMTMyMywiZXhwIjoxNjU4MzEyMjIzfQ.uT7_ei_vPuTljXEfo8L4i4x1yjlq4Vw4WYtrlbOyAqs

###

POST http://jobsify.dev/api/users/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkN2QwZmMzMGViYTk2Yjg3MTRjOTlkIiwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXIifSwiaWF0IjoxNjU4MzExMjMyLCJleHAiOjE2NTg5MTYwMzJ9.PNHQ9iShLy_EpiYVdFtRrAb4CbdBh8UlU78Tiw-Gttw

###

POST http://jobsify.dev/api/users/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkNzdkYTVlODQ3NTViNTA3MDE4MTc0Iiwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6InVzZXJteDEifSwiaWF0IjoxNjU4MjkwOTgxLCJleHAiOjE2NTgyOTE4ODF9.9T5D1GWsTW66VPaJ5JsK-98uC0VJ70tvPB8Vs7u7dhA
Content-Type: application/json

