POST http://jobsify.dev/api/jobs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkYTNmNjljZTRkYzAwZDcwY2I3ZjRmIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9LCJpYXQiOjE2NTg0NzAyNTEsImV4cCI6MTY1ODQ3MTE1MX0.SclKIFaiNjjZMZcznuyLU6BiPTWOdw3MlDzz8Mk5GEk
Content-Type: application/json

{
  "name": "Software Engineer",
  "company": "Google",
  "description": "We are looking for a software engineer to join our team.",
  "requirements": [
    "Must have a passion for software development",
    "Must be a good team player"
  ],
  "responsibilities": [
    "Write code",
    "Debug code",
    "Test code"
  ],
  "location": "New York, NY",
  "vacancy":10
}

###

GET http://jobsify.dev/api/jobs
Content-Type: application/json

###

DELETE http://jobsify.dev/api/jobs/62da414be5c7c5d38b2d8341
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkYTNmNjljZTRkYzAwZDcwY2I3ZjRmIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9LCJpYXQiOjE2NTg0NzAyNTEsImV4cCI6MTY1ODQ3MTE1MX0.SclKIFaiNjjZMZcznuyLU6BiPTWOdw3MlDzz8Mk5GEk
Content-Type: application/json

###

PATCH http://jobsify.dev/api/jobs/62da3f788292d7b636d0fa48
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ4LWpvYnNpZnkta2V5Ijp7ImlkIjoiNjJkYTNmNjljZTRkYzAwZDcwY2I3ZjRmIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9LCJpYXQiOjE2NTg0NzAyNTEsImV4cCI6MTY1ODQ3MTE1MX0.SclKIFaiNjjZMZcznuyLU6BiPTWOdw3MlDzz8Mk5GEk
Content-Type: application/json

{
  "name": "Software Engineer Updated 2",
  "vacancy": 100
}

###

GET http://jobsify.dev/api/jobs/62d8e94d3a6ea17e4890253f



