apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications
  template:
    metadata:
      labels:
        app: applications
    spec:
      containers:
        - name: applications
          image: pragusga/applications
          env:
            - name: MONGO_URI
              value: 'mongodb://applications-mongo-srv:27017/applications'
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-secret
                  key: JWT_REFRESH_TOKEN_SECRET
          resources:
            limits:
              memory: 100Mi
              cpu: '0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: applications-srv
spec:
  selector:
    app: applications
  ports:
    - name: applications
      protocol: TCP
      port: 3000
      targetPort: 3000
