apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications-mongo
  template:
    metadata:
      labels:
        app: applications-mongo
    spec:
      containers:
        - name: applications-mongo
          image: mongo:4.0-xenial
          resources:
            limits:
              cpu: '0.1'
            requests:
              cpu: '0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: applications-mongo-srv
spec:
  selector:
    app: applications-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
