apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
        - name: jobs
          image: pragusga/jobs
          env:
            - name: MONGO_URI
              value: 'mongodb://jobs-mongo-srv:27017/jobs'
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-secret
                  key: JWT_REFRESH_TOKEN_SECRET
          resources:
            limits:
              memory: 200Mi
              cpu: '0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-srv
spec:
  selector:
    app: jobs
  ports:
    - name: jobs
      protocol: TCP
      port: 3000
      targetPort: 3000
