name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save jobsify
      - run: kubectl apply -f k8s/common && kubectl apply -f k8s/prod
